### PR TITLE
Adding VuePress-plugin for Ackee

### PR DESCRIPTION
**Pull request by spekulatius**
Hey @electerious 

I've made a plugin for [VuePress for Ackee](https://github.com/spekulatius/vuepress-plugin-ackee). Just thought I add it to the list to let people know 💪️

Cheers!

### CODE REVIEW

**Comment by electerious** [comment]
I've changed the merge base. Let me know when the conflicts are resolved and I'm happy to merge it!

Thanks for creating a plugin for Ackee :)

**Comment by spekulatius** [comment]
Hey @electerious 

no problem! It's rebased. Please have another look and let me know if it works like this.

Cheers,
Peter

**Comment by electerious** [comment]
Thanks!

**Comment by spekulatius** [comment]
No worries :+1:

**Pull request merged**
