### PR TITLE
Add date range for top sort and add more data

### PR DESCRIPTION
**Pull request by RomainCscn**
## Description

- Add a way to change date range (**Last 7 days**, **Last 30 days**, **All time**) for top sort
- Add browser and screen resolution
- Add new label for recent and new sort instead of *Last 7 days*
- Add unit test for `getDateRange` function

## Screenshots

Screenshot 2020-04-10 at 12 05 00
Screenshot 2020-04-10 at 12 05 06
Screenshot 2020-04-10 at 12 05 10
Screenshot 2020-04-10 at 12 05 18
Screenshot 2020-04-10 at 12 05 21
Screenshot 2020-04-10 at 12 05 36

### CODE REVIEW

**Comment by electerious** [comment]
Shouldn't we remove the following code from the recent aggregations as it isn't "Last 7 days" anymore?

```
created: {
	$gte: subDays(zeroDate(), 6)
}
```

**Comment by RomainCscn** [comment]
Yes totally! I'm removing it as it does not make sense now.

**Comment by electerious** [comment]
Make sure to merge my changes before you continue https://github.com/electerious/Ackee/tree/RomainCscn-feature/add-top-date-range

**Comment by RomainCscn** [comment]
Ok will do! Thanks.

**Comment by RomainCscn** [comment]
I think we're good here @electerious, what do you think?

**Comment by electerious** [comment]
Merged it 👏

**Pull request merged**
