### PR TITLE
Support Qovery as a deployment option 

### PR DESCRIPTION
**Pull request by arnaudjnn**
Hi Ackee team,

I added docs on deploying Ackee to Qovery - feedback is welcome.

Arnaud.

### CODE REVIEW

**Comment by electerious** [comment]
Thanks for adding Qovery!

My suggestion is to reduce the number of lines for point 2, 3, 4 and 5. The Qovery part takes up a lot of space in the guide.

E.g. this is how step 5 could look like:
> Select "PostgreSQL" and a PostgreSQL version. Give the database a name and continue with "Next".

It would also be good to add a small info why PostgreSQL works when Ackee requires a MongoDB. I'm sure that I'm not the only one confused by this 😃

**Comment by BetaHuhn** [comment]
> It would also be good to add a small info why PostgreSQL works when Ackee requires a MongoDB. I'm sure that I'm not the only one confused by this 😃

When I saw the PR I was wondering the same, why does it work?! 😄

**Comment by arnaudjnn** [comment]
Hi @electerious,

I reduce each step according to your recommendations.

Let me know,

**Comment by electerious** [comment]
Thanks!

**Pull request merged**
