### PR TITLE
Fix annually month visits leaf query

### PR DESCRIPTION
**Pull request by jbleuzen**
If you use Ackee for more than year, you' ll have last year mont visits added to this year visits...

### CODE REVIEW

**Comment by electerious** [comment]
How about `SELECT strftime("%Y-%m", time, "unixepoch") date`?

**Comment by jbleuzen** [comment]
Yeah it might work also, but I don't know if it will display columns title correctly.
I'll try later today.

**Comment by electerious** [comment]
Good point. Let's leave it this way :)

**Comment by jbleuzen** [comment]
Ok, nice !

**Pull request merged**
