### PR TITLE
Support for custom authentication provider

### PR DESCRIPTION
**Pull request by PierreSchwang**
Implement support as described in #240

### CODE REVIEW

**Comment by PierreSchwang** [comment]
I'm unsure right now, theoretically it would work, but since the /api endpoint for ackee-tracker has to be public, doesn't that also mean that the GraphQL query to retrieve stats is now public as well? I don't know how to solve this at all....

**Comment by electerious** [comment]
@PierreSchwang How are you protecting the UI of Ackee? Isn't it possible to protect the API in the same way?

**Comment by PierreSchwang** [comment]
Yeah, but does the api not get used by the ackee script?

**Comment by electerious** [comment]
That's true. Not sure if there's a way to get around this problem. It's a GraphQL API so the endpoint for both ackee-tracker and Ackee is the same. This makes it impossible to allow ackee-tracker requests only.

**Comment by PierreSchwang** [comment]
Yeah, thats what i thought. I may take a further look into that

**Comment by electerious** [comment]
I will close the PR as there's currently no solution to solve the authentication problem.

**Pull request closed without merging**
